version: "2"
services:
    www:
        build: .
        ports: 
            - "8001:80"
        volumes:
            - ./server:/var/www/html/
        links:
            - db
            - mailhog:mailhog
        networks:
            - default
    db:
        image: mysql:5.7
        ports: 
            - "3306:3306"
        environment:
            MYSQL_DATABASE: camagru
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test 
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - persistent:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8000:80
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
    mailhog:
        image: mailhog/mailhog
        ports:
          - 1025:1025
          - 8025:8025
volumes:
    persistent:
